### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by CHEWX** [designloud/woocommerce-radio-buttons#1]
Hi, 

I've noticed this plugin needs an update to help with accessibility.

If I create a PR will it be merged, or are you not supporting this anymore.

Thanks.

**Comment by designloud** [comment]
It will be merged, we still support the plugin but due to our schedule I personally have not had time to much focus on this recently.  I have updated some things not yet merged to the repo but will try to get it done asap.  I would appreciate any help i can get keeping it updated :)
